### ISSUE TITLE
Define reading order of Settings in Mardi-Wikibase

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/docker-wikibase#18]
**Issue description**:
- To create deterministic behaviour in development and production for extensions etc 
- Order of settings can be set here, it would good practice to define an order Localsettings.d first then extensions or other:

[- https://github.com/MaRDI4NFDI/docker-wikibase/blob/main/LocalSettings.php.mardi.template](https://github.com/MaRDI4NFDI/docker-wikibase/blob/main/LocalSettings.php.mardi.template)
 
 
**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [x] Code was merged
- [x] Feature branch has been deleted and issues were updated / closed
- [ ] Issue has been estimated
