### ISSUE TITLE
Upgrade Mediawiki and Wikibase version

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/docker-wikibase#30]
**Issue description**:
To keep development synchronized with the latest Mediawiki/Wikibase/Extension changes. 
Versions should be set to latest releases.  

Also for importer and other than the main repo. 

**TODOS**: 
- [] Set Latest for Mediawiki
- [] Set Latest for Wikibase
- [] Set Latest for Extesions
- [] Deployment 

**Acceptance-Criteria** 
- Check if everything running smoothly locally 
- Everything running smoothly with the data which is already in production 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed

**Comment by Hyper-Node** [comment]
Composer v1 has to be used.
