### ISSUE TITLE
Automatic creation of Bot for import

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/docker-wikibase#51]
Look into automatic bot creation for the importer; alternatively get import to work without Bot
  
 

**Checklist for this issue**: 
(Some checks for making sure this feature-request is completely formulated)
- [ ] Participants in discussion have been invited as assignees 
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] MaRDI_Project has been assigned as project
