### ISSUE TITLE
Remove var/www/html in collector

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-wikibase#88]
**Issue description**:
In the collector stage we should remove the var/www/html directory before we start copying the extensions.
Otherwise we might create incompatibility issues between the lts mediawiki version and the cloned branch. 
 
**TODOS**: 
- [ ] RUN rm -r /var/www/html/* in the collector stage
- [ ] make sure the resulting image works

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
This has been now implemented: https://github.com/MaRDI4NFDI/docker-wikibase/commit/17463992e26c109f1b1b6f4edbff78e6be24c80f
